### ISSUE TITLE
How to add two or more tables in one query?

### ISSUE THREAD

**Issue by ahadziahmetovic** [syedhussim/php-sapb1#9]
I would like to add or join more tables in one query. Is it possible?

**Comment by Curadise** [comment]
Yes it is, however it's a bit complicated. You can look in the SAP Service Layer manual for the QueryService_PostQuery
Below is an example of joining and counting within the same query

`$query = ['QueryOption' => '$expand=Items($select=ItemCode)&$filter=Orders/DocEntry eq Orders/DocumentLines/DocEntry and Orders/DocumentLines/ItemCode eq Items/ItemCode and Orders/CardCode eq \'CUSTOMERCODE\'&$inlinecount=allpages&$apply=groupby((Items/ItemCode),aggregate(Orders(DocNum with count as DistinctDocNum)))&$orderby=Orders/DocNum desc', 'QueryPath' => '$crossjoin(Orders,Orders/DocumentLines,Items)'];

$sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
$orders = $sap->getService("QueryService_PostQuery");
$result = $orders->create($query);`

Also from SAP Version 10 up you can create custom SQL queries within the Service Layer and recall them later

**Comment by syedhussim** [comment]
Closing this issue

**Comment by gxb101** [comment]
Does anyone have an example of how we can use custom SQL queries vs. the QueryService_PostQuery approach above? It would be very helpful. Thanks in advance!

**Comment by Curadise** [comment]
This should do the trick (untested)
Creating a query:

```
$query = ['SqlCode' => 'CustomReport', 'SqlName' => 'CustomReport', 'SqlText' => 'SELECT t1.DocEntry, t1.DocNum, t2.CardName FROM ORDR t1 LEFT JOIN OCRD t2 ON t1.CardCode = t2.CardCode'];

$sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
$orders = $sap->getService("SQLQueries");
$result = $orders->create($query);
```

Updating the query:

```
$query = ['SqlCode' => 'CustomReport', 'SqlName' => 'CustomReport', 'SqlText' => 'SELECT t1.DocEntry, t1.DocNum, t2.CardCode, t2.CardName FROM ORDR t1 LEFT JOIN OCRD t2 ON t1.CardCode = t2.CardCode'];

$sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
$orders = $sap->getService("SQLQueries");
$result = $orders->update('CustomReport', $query);
```

Get the query:

```
$sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
$orders = $sap->getService('SQLQueries');

$result = $orders->queryBuilder()
    ->select('DocEntry, DocNum, CardCode, CardName')
    ->orderBy('DocNum', 'asc')
    ->limit(5)
    ->findAll();
```

**Comment by syedhussim** [comment]
I think you need to add the query code to the service name like the following.

`POST https://server:50000/b1s/v1/SQLQueries('CustomReport')/List `

**Comment by gxb101** [comment]
Appreciate the quick response on this one! Just looking at it, the "Get the Query" section above doesn't seem complete/correct. Why would you need to name the Select fields again since you already defined a query with them originally? I agree that the SQLCode identifier needs to be included in quotes along with the SQLQueries service call.  

My question is how to do you call that within the PHP code example provided?

Would it be something like this?

$sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
$orders = $sap->getService('SQLQueries(\'CustomReport\')/List');
and if so, how to obtain the $result variable?

I've tried a few variations on this, but no luck thus far.

**Comment by Curadise** [comment]
I've updated my query above for the GET. This is to view the query only, not to show results.

Currently checking out how to get the results from the /List parameter, but I thing @syedhussim knows better if this is possible

**Comment by gxb101** [comment]
> Yes it is, however it's a bit complicated. You can look in the SAP Service Layer manual for the QueryService_PostQuery Below is an example of joining and counting within the same query
> 
> ```
> $query = ['QueryOption' => '$expand=Items($select=ItemCode)&$filter=Orders/DocEntry eq Orders/DocumentLines/DocEntry and Orders/DocumentLines/ItemCode eq Items/ItemCode and Orders/CardCode eq \'CUSTOMERCODE\'&$inlinecount=allpages&$apply=groupby((Items/ItemCode),aggregate(Orders(DocNum with count as DistinctDocNum)))&$orderby=Orders/DocNum desc', 'QueryPath' => '$crossjoin(Orders,Orders/DocumentLines,Items)'];
> 
> $sap = SAPClient::createSession($config, 'SAP UserName', 'SAP Password', 'Company');
> $orders = $sap->getService("QueryService_PostQuery");
> $result = $orders->create($query);
> ```
> 
> Also from SAP Version 10 up you can create custom SQL queries within the Service Layer and recall them later

One additional question if you wouldn't mind regarding the building of the $query variable as mentioned above. How can I embed a custom variable into this string? For example, if I wanted to pass a DocEntry value (using a variable name) into this long string, what is the proper way to embed that? I am stuck because the query I am building works fine if I hardcode the DocEntry value as 12345, but if I want to use it inside the $query variable as $myDocNum, for example, the query fails. Not sure how to do this piece. Thanks in advance for your help with this!

**Comment by gxb101** [comment]
Hi guys, just circling back to see if anyone was able to determine how to call the custom query to get resulting data via PHP or how I could inject a custom variable into the $filter parameter inside of "QueryOption" (from my previous comment). Appreciate all your help.

**Comment by syedhussim** [comment]
Hi gxb101, to embed your custom value into the query,  you would just do string concatenation. Here is a javascript example, that I've used in another project.

``$expand=Orders($select=DocEntry,DocNum,DocDueDate,DocCurrency,DocTotalFc,Address,NumAtCard),Orders/DocumentLines($select=ItemCode,ItemDescription,Currency,Price,Quantity,LineTotal)
            &$filter=Orders/DocEntry eq Orders/DocumentLines/DocEntry 
            and Orders/DocEntry eq ${docEntry}``

As for the SQLQueries service, unfortunately, there is a bug in the library that is preventing it from working and I can't fix it due to maintaining backward compatibility. 

I may decide to work on a new version of this library to address some of the issues it currently has in the future.

**Comment by gxb101** [comment]
Hi Syed, appreciate the response.  The $query variable (see below) is already a string using reserved SQL variable names ($filter, $select, etc) denoted with a $ -- how can I then add my own variable ($myDocNum) to this string without breaking this query? The method you provided using brackets { }  does not work for PHP - I've tried multiple variations to try and escape the variable with no success. How would this need to be illustrated? 

The example below needs to Filter using a variable called $myDocEntry - I tried using brackets, but this doesn't work. Explicitly hard coding the DocNum (such as 12345) works perfectly. 

$query = ['QueryOption' => '$expand=Orders($select=DocEntry,DocNum,DocDueDate,DocCurrency,DocTotalFc,Address,NumAtCard),Orders/DocumentLines($select=ItemCode,ItemDescription,Currency,Price,Quantity,LineTotal) &$filter=Orders/DocEntry eq Orders/DocumentLines/DocEntry  and Orders/DocEntry eq {$myDocEntry}','QueryPath' => '$crossjoin(Orders, Orders/DocumentLines)'];

**Comment by gxb101** [comment]
Thanks for the reply -- I realized once you answered where I was going wrong - the comma after my variable separating the 1st and 2nd array element was confusing me, as I continually tried to concatenate that second element into the main string. All good now - much appreciated!
